# Generated by Django 3.1.2 on 2020-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='cell_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='images',
            name='component',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='images',
            name='doi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='images',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image_mode',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='organism',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='questions',
            name='answers_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='image_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='answers',
            name='definition',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
